---
env:
  REPO_NAME: registry.gitlab.com/southwinds/images
  IMG_NAME: openjdk
  IMG_TAG: 14-j9-ubi8-min
  JAVA_URL: https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.2%2B12_openj9-0.21.0/OpenJDK14U-jre_x64_linux_openj9_14.0.2_12_openj9-0.21.0.tar.gz
  JAVA_SHA256: 3a137146a7b0bd8b029e72beb37c5fbb09dcfb9e33a10125076fff1555227cfd
  JAVA_HOME: /usr/java/openjdk-14

functions:
  - name: build
    description: builds jdk base image
    run:
      - docker build -t ${REPO_NAME}/${IMG_NAME}:${IMG_TAG} --build-arg ${JAVA_URL} --build-arg ${JAVA_SHA256} --build-arg ${JAVA_HOME} .
...